#Draw a car:
import turtle
def draw_car():
    # Draw body
    turtle.color("red")
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(20)
    turtle.end_fill()
    # Draw wheels
    turtle.up()
    turtle.goto(25, -10)
    turtle.down()
    turtle.color("black")
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
    turtle.up()
    turtle.goto(70, -10)
    turtle.down()
    turtle.color("black")
    turtle.fillcolor("black")
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
draw_car()
turtle.done()